### ISSUE TITLE
Error: Uncaught (in promise): process is not defined message

### ISSUE THREAD

**Issue by shinokada** [bryanmylee/svelte-popperjs#25] opened 2022-09-01 06:41 UTC
I just copy and pasted the example in README and this is the [REPL link](https://svelte.dev/repl/d601322936f942508000f8824791af32?version=3.49.0).

As you see in the console, it returns an error and the example tooltip does not hide after `on:mouseleave`.

![image](https://user-images.githubusercontent.com/147320/187848741-d2631802-e9d4-4b65-b17f-e3f4e1c7ec61.png)

**Comment by bryanmylee** [comment] 2022-09-01 07:39
Hi @shinokada, thanks for the report. This is a duplicate of #7 and is unfortunately an issue with PopperJS itself.

PopperJS depends on the `process` global variable, but the Svelte REPL does not define `process`.

There should be no issues with SvelteKit or Vite as they both handle `process` properly.

If you're using Rollup, you can resolve this by using `rollup-plugin-replace`:

```
npm i -D @rollup/plugin-replace
```

Add the plugin to your Rollup config:

```
plugins: [
  replace({ 'process.env.NODE_ENV': JSON.stringify( 'production' ) }),
  // ...other plugins
]
```

**Closed as completed** 2022-09-12 08:18 UTC
